/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.gui.prints;

import com.github.sarxos.webcam.Webcam;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.ClaseLicenciaEnum;
import model.Licencia;
import model.Titular;
import util.TitularReceiver;
import view.gui.list.UserSeleccionarTitularPopUp;
import view.gui.menus.UserMenu;

/**
 *
 * @author lau_9
 */
public class UserPrintCarnet extends javax.swing.JFrame implements TitularReceiver {

    private Titular titular = null;
    private ClaseLicenciaEnum claseLicenciaEnum = null;
    private List<ClaseLicenciaEnum> clases = new ArrayList<ClaseLicenciaEnum>();
    private Collection<Licencia> licencias = new ArrayList<Licencia>();
    
    /**
     * Creates new form UserPrintCarnet
     */
    public UserPrintCarnet() {
        ImageIcon logo = new ImageIcon("src/res/drawable/sfc_logo.jpg");
        Image icon = logo.getImage();
        this.setIconImage(icon);
        initComponents();
        this.setLocationRelativeTo(null);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        btnLimpiarBusqueda = new javax.swing.JButton();
        btnBuscarTitular = new javax.swing.JButton();
        lblSantaFe = new javax.swing.JLabel();
        lblEmitirLicencia = new javax.swing.JLabel();
        pnlClases = new javax.swing.JPanel();
        chkA = new javax.swing.JCheckBox();
        chkB = new javax.swing.JCheckBox();
        chkC = new javax.swing.JCheckBox();
        chkD = new javax.swing.JCheckBox();
        chkE = new javax.swing.JCheckBox();
        chkF = new javax.swing.JCheckBox();
        chkG = new javax.swing.JCheckBox();
        lblFotoTitular = new javax.swing.JLabel();
        btnTomarFoto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPrevisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GLC | SFC - Imprimir Carnets");
        setResizable(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setText("Nombre del Titular");

        txtTitular.setEditable(false);
        txtTitular.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitularActionPerformed(evt);
            }
        });

        btnLimpiarBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/cancel_mini.png"))); // NOI18N
        btnLimpiarBusqueda.setToolTipText("Limpie el titular seleccionado");
        btnLimpiarBusqueda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBusquedaActionPerformed(evt);
            }
        });

        btnBuscarTitular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/search_mini.png"))); // NOI18N
        btnBuscarTitular.setToolTipText("Busque el titular para el cual quiere imprimir la licencia");
        btnBuscarTitular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTitularActionPerformed(evt);
            }
        });

        lblSantaFe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSantaFe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/drawable/logo-santafe.png"))); // NOI18N
        lblSantaFe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblEmitirLicencia.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        lblEmitirLicencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmitirLicencia.setText("IMPRIMIR CARNETS");

        pnlClases.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clases Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), java.awt.SystemColor.textHighlight)); // NOI18N

        chkA.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkA.setText("A");
        chkA.setToolTipText("Ciclomotores, motocicletas y triciclos motorizados");
        chkA.setEnabled(false);

        chkB.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkB.setText("B");
        chkB.setToolTipText("Automóviles y camionetas con acoplado");
        chkB.setEnabled(false);

        chkC.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkC.setText("C");
        chkC.setToolTipText("Camiones sin acoplado y los comprendidos en la clase B");
        chkC.setEnabled(false);

        chkD.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkD.setText("D");
        chkD.setToolTipText("Servicio de transporte de pasajeros, emergencia, seguridad y los comprendidos en la clase B o C, según el caso");
        chkD.setEnabled(false);

        chkE.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkE.setText("E");
        chkE.setToolTipText("Camiones articulados o con acoplado, maquinaria especial no agrícola y los comprendidos en la clase B y C");
        chkE.setEnabled(false);

        chkF.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkF.setText("F");
        chkF.setToolTipText("Automotores especialmente adaptados para discapacitados");
        chkF.setEnabled(false);

        chkG.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkG.setText("G");
        chkG.setToolTipText("Tractores agrícolas y maquinaria especial agrícola");
        chkG.setEnabled(false);

        javax.swing.GroupLayout pnlClasesLayout = new javax.swing.GroupLayout(pnlClases);
        pnlClases.setLayout(pnlClasesLayout);
        pnlClasesLayout.setHorizontalGroup(
            pnlClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClasesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkA)
                    .addComponent(chkB)
                    .addComponent(chkC)
                    .addComponent(chkD)
                    .addComponent(chkE)
                    .addComponent(chkF)
                    .addComponent(chkG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClasesLayout.setVerticalGroup(
            pnlClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkG)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFotoTitular.setBackground(new java.awt.Color(255, 255, 255));
        lblFotoTitular.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblFotoTitular.setForeground(new java.awt.Color(0, 0, 0));
        lblFotoTitular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoTitular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/drawable/user.png"))); // NOI18N
        lblFotoTitular.setText(".");
        lblFotoTitular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFotoTitular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFotoTitular.setOpaque(true);

        btnTomarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/camera_mini.png"))); // NOI18N
        btnTomarFoto.setText("Tomar Foto");
        btnTomarFoto.setEnabled(false);
        btnTomarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarFotoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(btnCancelar.getFont().deriveFont(btnCancelar.getFont().getSize()+2f));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/previous_mini.png"))); // NOI18N
        btnCancelar.setText("Volver");
        btnCancelar.setToolTipText("Cancelar la operación y volver al menu");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPrevisualizar.setFont(btnPrevisualizar.getFont().deriveFont(btnPrevisualizar.getFont().getSize()+2f));
        btnPrevisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/preview_carnet.png"))); // NOI18N
        btnPrevisualizar.setText("Previsualizar");
        btnPrevisualizar.setToolTipText("Ver la vista previa de las licencias seleccionadas");
        btnPrevisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmitirLicencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSantaFe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlClases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTomarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrevisualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblFotoTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSantaFe, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEmitirLicencia)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscarTitular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpiarBusqueda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFotoTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTomarFoto))
                    .addComponent(pnlClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitularActionPerformed

    private void btnLimpiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBusquedaActionPerformed

        if(titular != null){
            titular = null;
            clases = null;
            licencias = null;
            txtTitular.setText("");
            this.chkA.setSelected(false);
            this.chkB.setSelected(false);
            this.chkC.setSelected(false);
            this.chkD.setSelected(false);
            this.chkE.setSelected(false);
            this.chkF.setSelected(false);
            this.chkG.setSelected(false);
            this.chkA.setEnabled(false);
            this.chkB.setEnabled(false);
            this.chkC.setEnabled(false);
            this.chkD.setEnabled(false);
            this.chkE.setEnabled(false);
            this.chkF.setEnabled(false);
            this.chkG.setEnabled(false);
            btnTomarFoto.setEnabled(false);
            lblFotoTitular.setIcon(new ImageIcon("src\\res\\drawable\\user.png"));
            lblFotoTitular.setText(".");
            
        }

    }//GEN-LAST:event_btnLimpiarBusquedaActionPerformed

    private void btnBuscarTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTitularActionPerformed
        new UserSeleccionarTitularPopUp(this).setVisible(true);
        this.chkA.setSelected(false);
        this.chkB.setSelected(false);
        this.chkC.setSelected(false);
        this.chkD.setSelected(false);
        this.chkE.setSelected(false);
        this.chkF.setSelected(false);
        this.chkG.setSelected(false);
        this.chkA.setEnabled(false);
        this.chkB.setEnabled(false);
        this.chkC.setEnabled(false);
        this.chkD.setEnabled(false);
        this.chkE.setEnabled(false);
        this.chkF.setEnabled(false);
        this.chkG.setEnabled(false);
        
    }//GEN-LAST:event_btnBuscarTitularActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Integer respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea volver al Menu?", "Volver",  JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
                new UserMenu().setVisible(true);
                this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPrevisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevisualizarActionPerformed
        List<Licencia> licSeleccionadas = new ArrayList<Licencia>();
        Date fechaActual = new Date();
        
        for(Licencia lic : licencias){
            Date fechaVencimiento = lic.getFechaVencimiento();
                if(lic.isActiva() && fechaVencimiento.after(fechaActual)){
                    switch(lic.getClaseLicenciaEnum()){
                        case A: if(chkA.isSelected()) { licSeleccionadas.add(lic); }; break;
                        case B: if(chkB.isSelected()) { licSeleccionadas.add(lic); }; break;
                        case C: if(chkC.isSelected()) { licSeleccionadas.add(lic); }; break;
                        case D: if(chkD.isSelected()) { licSeleccionadas.add(lic); }; break;
                        case E: if(chkE.isSelected()) { licSeleccionadas.add(lic); }; break;
                        case F: if(chkF.isSelected()) { licSeleccionadas.add(lic); }; break;
                        case G: if(chkG.isSelected()) { licSeleccionadas.add(lic); }; break;
                    }
                }
            }
        
        if(!licSeleccionadas.isEmpty() && !(lblFotoTitular.getText().equals("."))){
            new UserPreviewCarnetPopUp(titular, licSeleccionadas).setVisible(true);
        } else {
            if("".equals(txtTitular.getText())){
                JOptionPane.showMessageDialog(this, "Debe seleccionar algún titular.", "Atención", JOptionPane.WARNING_MESSAGE);
            } else { 
                JOptionPane.showMessageDialog(this, "Debe seleccionar alguna clase y tomar una foto del titular.", "Atención", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnPrevisualizarActionPerformed

    private void btnTomarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarFotoActionPerformed
        lblFotoTitular.setText("");
        
        // Inicializo la webcam y tomo la foto
	Webcam webcam = Webcam.getDefault();
        webcam.setViewSize(new Dimension(640, 480));
	webcam.open();
	BufferedImage imagen = webcam.getImage();
        webcam.close();
        
        // Guardo la foto con su resolucion original
        try {
            ImageIO.write(imagen, "PNG", new File("test.png"));
        } catch (IOException ex) {
            Logger.getLogger(UserPrintCarnet.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Muestro la foto tomada en la interfaz
        try {
            lblFotoTitular.setIcon( new ImageIcon(ImageIO.read(new File("test.png"))));
        } catch (IOException ex) {
            Logger.getLogger(UserPrintCarnet.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Guardo la foto en la resolucion necesitada (256x256 - tamanio del label que la contiene)
        BufferedImage img = new BufferedImage(lblFotoTitular.getWidth(), lblFotoTitular.getHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = img.createGraphics();
        lblFotoTitular.printAll(g2d);
        g2d.dispose();
        try {
            ImageIO.write(img, "JPG", new File("fotoTitular.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(UserPrintCarnet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTomarFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPrintCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPrintCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPrintCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPrintCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPrintCarnet().setVisible(true);
            }
        });
    }
    
    @Override
    public void setTitularRecibido(Titular titular) {
        Date fechaActual = new Date();
        this.titular = titular;
        this.clases = titular.getClases();
        this.licencias = titular.getLicencias();
        this.txtTitular.setText(titular.getApellido()+", "+titular.getNombre());
        
        if(clases.isEmpty()){
            JOptionPane.showMessageDialog(this, "El titular seleccionado no posee licencias registradas.", "Error", JOptionPane.ERROR_MESSAGE);
            this.txtTitular.setText("");
        }
        else{
            
            for(Licencia lic : licencias){
                if(lic.isActiva() && fechaActual.before(lic.getFechaVencimiento())){
                    switch(lic.getClaseLicenciaEnum()){
                        case A: chkA.setEnabled(true); break;
                        case B: chkB.setEnabled(true); break;
                        case C: chkC.setEnabled(true); break;
                        case D: chkD.setEnabled(true); break;
                        case E: chkE.setEnabled(true); break;
                        case F: chkF.setEnabled(true); break;
                        case G: chkG.setEnabled(true); break;
                    }
                    btnTomarFoto.setEnabled(true);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTitular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiarBusqueda;
    private javax.swing.JButton btnPrevisualizar;
    private javax.swing.JButton btnTomarFoto;
    private javax.swing.JCheckBox chkA;
    private javax.swing.JCheckBox chkB;
    private javax.swing.JCheckBox chkC;
    private javax.swing.JCheckBox chkD;
    private javax.swing.JCheckBox chkE;
    private javax.swing.JCheckBox chkF;
    private javax.swing.JCheckBox chkG;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEmitirLicencia;
    private javax.swing.JLabel lblFotoTitular;
    private javax.swing.JLabel lblSantaFe;
    private javax.swing.JPanel pnlClases;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}