/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.gui.menus;

import java.awt.Color;
import view.gui.abm.*;
import view.gui.login.MainMenu;

/**
 *
 * @author lau_9
 */
public class UserMenu extends javax.swing.JFrame {

    /** Creates new form userMenu */
    public UserMenu() {
        initComponents();
        btnLogout.setBackground(Color.red);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSantaFe = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnAddUser1 = new javax.swing.JButton();
        btnAddUser2 = new javax.swing.JButton();
        btnAddUser3 = new javax.swing.JButton();
        btnAddUser4 = new javax.swing.JButton();
        btnAddUser5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Licencias de Conducir");
        setType(java.awt.Window.Type.UTILITY);

        lblSantaFe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/drawable/logo-santafe.png"))); // NOI18N
        lblSantaFe.setText("jLabel1");

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/logout2.png"))); // NOI18N
        btnLogout.setToolTipText("Cerrar Sesión");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAddUser.setFont(btnAddUser.getFont().deriveFont(btnAddUser.getFont().getSize()+3f));
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/list_vencidas.png"))); // NOI18N
        btnAddUser.setText("Listado de Licencias Vencidas");
        btnAddUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAddUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnAddUser1.setFont(btnAddUser1.getFont().deriveFont(btnAddUser1.getFont().getSize()+3f));
        btnAddUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/add_titular.png"))); // NOI18N
        btnAddUser1.setText("Agregar Titulares");
        btnAddUser1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddUser1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAddUser1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUser1ActionPerformed(evt);
            }
        });

        btnAddUser2.setFont(btnAddUser2.getFont().deriveFont(btnAddUser2.getFont().getSize()+3f));
        btnAddUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/renew_licencia.png"))); // NOI18N
        btnAddUser2.setText("Renovar Licencias");
        btnAddUser2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddUser2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAddUser2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUser2ActionPerformed(evt);
            }
        });

        btnAddUser3.setFont(btnAddUser3.getFont().deriveFont(btnAddUser3.getFont().getSize()+3f));
        btnAddUser3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/duplicate_licencia.png"))); // NOI18N
        btnAddUser3.setText("Copiar Licencias");
        btnAddUser3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddUser3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAddUser3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUser3ActionPerformed(evt);
            }
        });

        btnAddUser4.setFont(btnAddUser4.getFont().deriveFont(btnAddUser4.getFont().getSize()+3f));
        btnAddUser4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/list_ok.png"))); // NOI18N
        btnAddUser4.setText("Listado de Licencias Vigentes");
        btnAddUser4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddUser4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAddUser4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddUser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUser4ActionPerformed(evt);
            }
        });

        btnAddUser5.setFont(btnAddUser5.getFont().deriveFont(btnAddUser5.getFont().getSize()+3f));
        btnAddUser5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/new_licencia.png"))); // NOI18N
        btnAddUser5.setText("Emitir Licencia");
        btnAddUser5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddUser5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAddUser5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddUser5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUser5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSantaFe, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddUser5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSantaFe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddUser1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddUser5)
                .addGap(5, 5, 5)
                .addComponent(btnAddUser2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddUser3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddUser4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnAddUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUser1ActionPerformed
        // TODO add your handling code here:
        new UserAddTitular().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddUser1ActionPerformed

    private void btnAddUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddUser2ActionPerformed

    private void btnAddUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddUser3ActionPerformed

    private void btnAddUser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUser4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddUser4ActionPerformed

    private void btnAddUser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUser5ActionPerformed
        new UserEmitirLicencia().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddUser5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAddUser1;
    private javax.swing.JButton btnAddUser2;
    private javax.swing.JButton btnAddUser3;
    private javax.swing.JButton btnAddUser4;
    private javax.swing.JButton btnAddUser5;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel lblSantaFe;
    // End of variables declaration//GEN-END:variables

}
